# RTX 4060 单GPU 百万级数据集优化配置 / RTX 4060 Single GPU Configuration for Million-scale Dataset
# 针对8GB显存优化 / Optimized for 8GB VRAM

model:
  name: SpectralResNet1D
  num_blocks: 12  # 可以适当减少以节省内存 / Can be reduced to save memory
  channels: 64    # 可以调整为48或32如果内存不足 / Can be adjusted to 48 or 32 if memory is insufficient
  input_channels: 1

training:
  num_epochs: 100
  batch_size: 64  # 从小批次开始，逐步增加 / Start with small batch size, gradually increase
  learning_rate: 0.0005
  weight_decay: 0.00001
  optimizer: adam
  gradient_accumulation_steps: 4  # 有效批次=64*4=256 / Effective batch size = 64*4=256
  gradient_clip: 1.0
  mixed_precision: true  # 必须开启！ / Must be enabled!

loss:
  type: optimized  # 使用优化的损失函数 / Use optimized loss function
  peak_weight: 10.0
  compton_weight: 1.0
  smoothness_weight: 0.1
  frequency_weight: 0.1

data:
  format: h5  # 使用标准H5格式 / Use standard H5 format
  train_path: dataset_split/train  # 自动分割后的训练数据路径 / Training data path after automatic split
  val_path: dataset_split/val      # 自动分割后的验证数据路径 / Validation data path after automatic split
  num_workers: 0  # Windows下设置为0避免多进程问题 / Set to 0 on Windows to avoid multiprocessing issues
  pin_memory: true
  normalize: true
  cache_size: 200  # 适当的缓存大小 / Appropriate cache size
  use_mmap: true
  prefetch_factor: 2

metrics:
  use_efficient_metrics: true  # GPU加速指标 / GPU-accelerated metrics

logging:
  log_dir: logs
  checkpoint_dir: checkpoints
  save_interval: 10  # 每10个epoch保存 / Save every 10 epochs
  log_interval: 100  # 减少日志频率 / Reduce logging frequency
  val_interval: 1

device:
  use_cuda: true
  device_id: 0
  mixed_precision: true